fcnn7:
  network: nets/fcnn7.onnx
  dataset: mnist
  strategy:
      - type: 1

fconv4:
  network: nets/fconv4.onnx
  dataset: mnist
  strategy:
      - type: 1

fcnn7_cifar:
  network: nets/fcnn7_cifar.onnx
  dataset: cifar10
  strategy:
      - type: 1

fconv4_cifar:
  network: nets/fconv4_cifar.onnx
  anetwork: nets/fconv4_cifar_quant8.onnx
  dataset: cifar10
  strategy:
      - type: 1
